services:
  api:
    container_name: philoagents-api
    build:
      context: ./philoagents-api
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb+srv://chudasamayash:1rae1NkzHTpVCcGn@clusterphiloagents.sh1rkgk.mongodb.net/philoagents?retryWrites=true&w=majority
    ports:
      - "8000:8000"
    env_file:
      - ./philoagents-api/.env
    networks:
      - philoagents-network
  ui:
    container_name: philoagents-ui
    build:
      context: ./philoagents-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./philoagents-ui:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - philoagents-network

volumes:
  data:
  config:

networks:
  philoagents-network:
    name: philoagents-network